import path from "node:path";
import { stringify } from "smol-toml";
import { expandHome, profileConfigsDir, type RuntimePaths } from "../core/paths.js";
import { parseEnvRef } from "../core/env-ref.js";
import {
  deepMerge,
  executorBridgeName,
  filterMcpForTarget,
  requiresExecutorBridge,
  skillRuntimeDefaults,
  type ResolvedProfile
} from "../core/profile.js";
import type { RenderResult } from "../core/render.js";
import { renderInlinedAgents } from "./agents-doc.js";
import { readTomlObject } from "../core/fs-util.js";
import { hasManagedZsh, zshSecretsDir } from "../core/zsh.js";
import { mergeSkillOverrides } from "../core/skill-overrides.js";
import { codexExecutorEntry } from "./executor.js";

export const CODEX_DERIVED_KEYS = new Set([
  "mcp_servers",
  "permissions",
  "default_permissions",
  "plugins",
  "skills"
]);

function renderCodexMcp(paths: RuntimePaths, profile: ResolvedProfile): Record<string, unknown> {
  const mcp = Object.fromEntries(
    filterMcpForTarget(profile, "codex").map(({ name, server, enabled }) => {
      if (server.type === "remote") {
        const literalHeaders: Record<string, string> = {};
        const envHeaders: Record<string, string> = {};
        for (const [header, value] of Object.entries(server.headers ?? {})) {
          const envVar = parseEnvRef(value);
          if (envVar !== null) {
            envHeaders[header] = envVar;
          } else {
            literalHeaders[header] = value;
          }
        }
        return [
          name,
          {
            url: server.url,
            enabled,
            ...(Object.keys(literalHeaders).length > 0 ? { http_headers: literalHeaders } : {}),
            ...(Object.keys(envHeaders).length > 0 ? { env_http_headers: envHeaders } : {})
          }
        ];
      }

      const [command, ...args] = server.command.map((part) => expandHome(part, paths.home));
      return [
        name,
        {
          command,
          ...(args.length > 0 ? { args } : {}),
          enabled,
          ...(server.env ? { env: server.env } : {})
        }
      ];
    })
  );
  if (requiresExecutorBridge(profile)) mcp[executorBridgeName] = codexExecutorEntry(profile);
  return mcp;
}

function renderCodexPermissions(
  paths: RuntimePaths,
  profile: ResolvedProfile
): Record<string, unknown> {
  const filesystem: Record<string, string> = {
    [profile.referencesDir]: "read"
  };

  if (hasManagedZsh(profile)) {
    filesystem[zshSecretsDir(paths)] = "deny";
  }

  for (const folder of profile.extraFolders) {
    const absPath = expandHome(folder.path, paths.home);
    filesystem[absPath] = codexFolderPermission(folder.read, folder.edit);
  }

  return {
    default_permissions: "mfz",
    permissions: {
      mfz: {
        description: "Generated by mindframe-z",
        filesystem
      }
    }
  };
}

function codexFolderPermission(read: string, edit: string): "deny" | "read" | "write" {
  if (read === "deny" || edit === "deny") return "deny";
  if (edit === "allow") return "write";
  return "read";
}

export function renderCodexPlugins(
  profile: ResolvedProfile
): Record<string, { enabled: boolean; toggleable?: boolean }> {
  return Object.fromEntries(
    Object.entries(profile.profile.codex.plugins).map(([id, plugin]) => [
      id,
      {
        enabled: plugin.enabled,
        ...(plugin.toggleable === undefined ? {} : { toggleable: plugin.toggleable })
      }
    ])
  );
}

export async function renderCodex(
  paths: RuntimePaths,
  profile: ResolvedProfile
): Promise<RenderResult> {
  const configsCodex = path.join(profileConfigsDir(paths, profile.name), "codex");
  const configPath = path.join(configsCodex, "config.toml");
  const agentsPath = path.join(configsCodex, "AGENTS.md");

  const plugins = renderCodexPlugins(profile);
  const hasPlugins = Object.keys(plugins).length > 0;
  const config = deepMerge(profile.profile.codex.config, {
    ...renderCodexPermissions(paths, profile),
    mcp_servers: renderCodexMcp(paths, profile),
    ...(hasPlugins ? { plugins } : {})
  });
  const skillDefaults = skillRuntimeDefaults(profile, "codex");
  const skillPaths = Object.fromEntries(
    Object.keys(skillDefaults).map((name) => [
      name,
      path.join(paths.home, ".agents", "skills", name, "SKILL.md")
    ])
  );
  const renderedConfig = mergeSkillOverrides("codex", config, skillDefaults, { skillPaths });
  const configContent = stringify(renderedConfig);
  const agentsContent = await renderInlinedAgents(paths, profile);
  const localConfigPath = path.join(paths.codexDir, "config.toml");
  const mergedLocalConfig = deepMerge(await readTomlObject(localConfigPath), renderedConfig);
  if (hasPlugins) {
    mergedLocalConfig.plugins = config.plugins;
  } else {
    delete mergedLocalConfig.plugins;
  }

  return {
    files: [
      { path: configPath, content: configContent },
      { path: agentsPath, content: agentsContent }
    ],
    localFiles: [
      { path: localConfigPath, content: stringify(mergedLocalConfig) },
      { path: path.join(paths.codexDir, "AGENTS.md"), content: agentsContent }
    ],
    links: []
  };
}
