import { readFile } from "node:fs/promises";
import path from "node:path";
import { stringify } from "smol-toml";
import { expandHome, profileConfigsDir, type RuntimePaths } from "../core/paths.js";
import { deepMerge, filterMcpForTarget, type ResolvedProfile } from "../core/profile.js";
import type { RenderResult } from "../core/render.js";
import { readTomlObject } from "../core/skill-overrides.js";
import { hasManagedZsh, zshSecretsDir } from "../core/zsh.js";

export const CODEX_DERIVED_KEYS = new Set(["mcp_servers", "permissions", "default_permissions"]);

function renderCodexMcp(profile: ResolvedProfile, home: string): Record<string, unknown> {
  return Object.fromEntries(
    filterMcpForTarget(profile, "codex").map(({ name, server, enabled }) => {
      if (server.type === "remote") {
        return [
          name,
          {
            url: server.url,
            enabled,
            ...(server.headers ? { http_headers: server.headers } : {})
          }
        ];
      }

      const [command, ...args] = server.command.map((part) => expandHome(part, home));
      return [
        name,
        {
          command,
          ...(args.length > 0 ? { args } : {}),
          enabled,
          ...(server.env ? { env: server.env } : {})
        }
      ];
    })
  );
}

function renderCodexPermissions(
  paths: RuntimePaths,
  profile: ResolvedProfile
): Record<string, unknown> {
  const filesystem: Record<string, string> = {
    [profile.referencesDir]: "read"
  };

  if (hasManagedZsh(profile)) {
    filesystem[zshSecretsDir(paths)] = "deny";
  }

  for (const folder of profile.extraFolders) {
    const absPath = expandHome(folder.path, paths.home);
    filesystem[absPath] = codexFolderPermission(folder.read, folder.edit);
  }

  return {
    default_permissions: "mfz",
    permissions: {
      mfz: {
        description: "Generated by mindframe-z",
        filesystem
      }
    }
  };
}

function codexFolderPermission(read: string, edit: string): "deny" | "read" | "write" {
  if (read === "deny" || edit === "deny") return "deny";
  if (edit === "allow") return "write";
  return "read";
}

async function renderCodexAgents(paths: RuntimePaths, profile: ResolvedProfile): Promise<string> {
  const parts: string[] = [];
  for (const file of profile.instructionFiles) parts.push(await readFile(file, "utf8"));
  for (const file of [
    path.join(paths.home, ".mindframe-z", "references.md"),
    ...(profile.extraFolders.length > 0
      ? [path.join(paths.home, ".mindframe-z", "extra_folders.md")]
      : [])
  ]) {
    try {
      parts.push(await readFile(file, "utf8"));
    } catch {
      // Dry-run renders may happen before local indexes are written.
    }
  }
  return (
    parts
      .map((part) => part.trim())
      .filter(Boolean)
      .join("\n\n") + "\n"
  );
}

export async function renderCodex(
  paths: RuntimePaths,
  profile: ResolvedProfile
): Promise<RenderResult> {
  const configsCodex = path.join(profileConfigsDir(paths, profile.name), "codex");
  const configPath = path.join(configsCodex, "config.toml");
  const agentsPath = path.join(configsCodex, "AGENTS.md");

  const config = deepMerge(profile.profile.codex.config, {
    ...renderCodexPermissions(paths, profile),
    mcp_servers: renderCodexMcp(profile, paths.home)
  });
  const configContent = stringify(config);
  const agentsContent = await renderCodexAgents(paths, profile);
  const localConfigPath = path.join(paths.codexDir, "config.toml");
  const mergedLocalConfig = deepMerge(await readTomlObject(localConfigPath), config);

  return {
    files: [
      { path: configPath, content: configContent },
      { path: agentsPath, content: agentsContent }
    ],
    localFiles: [
      { path: localConfigPath, content: stringify(mergedLocalConfig) },
      { path: path.join(paths.codexDir, "AGENTS.md"), content: agentsContent }
    ],
    links: []
  };
}
